#!/bin/bash
#
# ## Plugin for Munin to monitor reported uncorrect
# Author: Okumura Takahiro <hfm.garden@gmail.com>
#
# ## Description:
#
# This plugin uses smartctl command to get the number of reported uncorrect (S.M.A.R.T ID:187).
#
# sample conf
# [uncorrect_sector]
# user root
#
#%# family=auto
#%# capabilities=autoconf

LANG=C
export PATH=$PATH:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

# Defaulh threshold
warning="10:19"
critical="20:"

smartctl=$(which smartctl)
if [ "$1" = "autoconf" ]; then
    if [ -x "$smartctl" ]; then
        echo yes
        exit 0
    else
        echo "no (smartctl is not exist.)"
        exit 1
    fi
fi

# get device list like (sda sda1 sda2 sdb ...)
partitions=$(awk '$4 ~ /^[a-z]d[a-z]+$/ {print $4}' /proc/partitions)

devs=""
for part in $partitions; do
    $smartctl -A /dev/$part -d auto | grep -q '^187 ' || continue
    devs="$devs $part"
done

if [ "$1" = "config" ]; then
    echo 'graph_title Reported_Uncorrect'
    echo 'graph_args --alt-y-grid --base 1000 -l 0'
    echo 'graph_vlabel the number'
    echo 'graph_category disk'
    echo 'graph_info This graph shows Reported_Uncorrect (SMART ID:187).'

    for dev in $devs; do
        echo "${dev}.label $dev"
        echo "${dev}.warning $warning"
        echo "${dev}.critical $critical"
        echo "${dev}.type GAUGE"
    done
    exit 0
fi

for dev in $devs; do
    echo -n "${dev}.value "
    smartctl -A /dev/$dev -d auto | awk '$1==187 {print $NF}'
done
